SELECT ADDRESS FROM STUDIO
WHERE name='MGM';

SELECT BIRTHDATE FROM MOVIESTAR
WHERE name = 'Sandra Bullock'

SELECT STARNAME FROM STARSIN
WHERE MOVIEYEAR = '1980'
AND MOVIETITLE LIKE '%Empire%';


SELECT NAME, NETWORTH FROM MOVIEEXEC
WHERE NETWORTH > 10000000; 


SELECT NAME FROM MOVIESTAR
WHERE GENDER = 'M' OR ADDRESS = 'Malibu'

