
--CREATE view Cl_ships
--AS 
--SELECT * FROM CLASSES WHERE COUNTRY = 'USA'


--DROP VIEW Cl_ships

--ZADACHKI

--CREATE VIEW Actress_name_birthday AS
--SELECT NAME, BIRTHDATE FROM MOVIESTAR WHERE GENDER = 'F'

--CREATE VIEW actor_num(name, num) AS 
--SELECT NAME, COUNT(MOVIETITLE) FROM MOVIESTAR M
--JOIN STARSIN SI ON SI.STARNAME = M.NAME
--GROUP BY M.NAME

--CREATE VIEW laptop_pc_printer AS
--((SELECT CODE, MODEL, PRICE FROM LAPTOP)
--UNION
--(SELECT CODE, MODEL, PRICE FROM PC)
--UNION
--(SELECT CODE, MODEL, PRICE FROM PRINTER))

--DROP VIEW laptop_pc_printer

--CREATE VIEW laptop_pc_printer AS
--SELECT CODE, MODEL, PRICE, 'Laptop' AS TYPE, SPEED FROM LAPTOP
--UNION ALL
--SELECT CODE, MODEL, PRICE, 'PC' AS TYPE, SPEED FROM PC
--UNION ALL
--SELECT CODE, MODEL, PRICE, 'Printer' AS TYPE, NULL AS SPEED FROM PRINTER;

--SHIPS

--CREATE VIEW british_ship AS
--SELECT CL.CLASS, TYPE, NUMGUNS, BORE, DISPLACEMENT, LAUNCHED  FROM SHIPS SH
--JOIN CLASSES CL ON CL.CLASS = SH.CLASS
--WHERE COUNTRY = 'Gt. Britain'


--ALTER VIEW british_ship AS
--SELECT NUMGUNS, DISPLACEMENT FROM SHIPS SH
--JOIN CLASSES CL ON CL.CLASS = SH.CLASS
--WHERE TYPE = 'BB' AND LAUNCHED < 1919 AND COUNTRY = 'Gt. Britain'

--SELECT CLASS, AVG(DISPLACEMENT) AS AVERAGE FROM CLASSES WHERE CLASS IN (SELECT C1.CLASS FROM CLASSES C1
--WHERE C1.DISPLACEMENT IN (SELECT MAX(C2.DISPLACEMENT) FROM CLASSES C2 WHERE C2.COUNTRY = C1.COUNTRY))
--GROUP BY CLASS

--CREATE VIEW sunk_ships AS 
--SELECT BATTLE, SHIP FROM OUTCOMES
--WHERE RESULT = 'SUNK'

--ALTER TABLE Outcomes
--ADD CONSTRAINT DF_Result_Sunk DEFAULT NULL FOR RESULT;

--ALTER TABLE OUTCOMES
--DROP  DF_Result_Sunk

--ALTER TABLE Outcomes
--ADD CONSTRAINT DF_RES_SUNK DEFAULT 'sunk' FOR RESULT

--INSERT INTO sunk_ships (BATTLE, SHIP)
--VALUES ('Guadalcanal', 'Fuso')

--CREATE VIEW nine_guns AS
--SELECT * FROM CLASSES 
--WHERE NUMGUNS >= 9
--WITH CHECK OPTION

--това успя
--UPDATE nine_guns 
--SET NUMGUNS = 15
--WHERE CLASS = 'Iowa'

--това не успя, щото 6 няма да се опакже след WITH CHECK OPTION
--UPDATE nine_guns
--SET NUMGUNS = 5
--WHERE CLASS = 'Iowa'


--ALTER VIEW nine_guns AS
--SELECT * FROM CLASSES

--CREATE VIEW complicated_battles AS
--SELECT BATTLE FROM OUTCOMES OT
--JOIN SHIPS SH ON SH.NAME = OT.SHIP
--JOIN CLASSES CL ON SH.CLASS = CL.CLASS
--WHERE NUMGUNS < 9 
--GROUP BY BATTLE
--HAVING COUNT(SHIP) >= 3 AND SUM(CASE WHEN RESULT = 'damaged' THEN 1 ELSE 0 END) >= 1 



