--filmi
--SELECT ADDRESS FROM STUDIO WHERE NAME = 'MGM';

--SELECT BIRTHDATE FROM MOVIESTAR WHERE NAME = 'Sandra Bullock';

--SELECT STARNAME FROM STARSIN WHERE MOVIEYEAR = 1980 AND MOVIETITLE LIKE '%Empire%';

--SELECT NAME FROM MOVIEEXEC WHERE NETWORTH > 10000 ;

--SELECT * FROM MOVIESTAR WHERE GENDER = 'm' OR ADDRESS LIKE '%Malibu%' ;

---pc
--SELECT model, speed AS MHz, hd AS GB FROM LAPTOP WHERE PRICE < 1200;

--SELECT MODEL, PRICE*1.1 AS EURO FROM LAPTOP ORDER BY PRICE ASC;

--SELECT MODEL, RAM, SCREEN FROM LAPTOP WHERE PRICE > 1000; 

--SELECT * FROM printer WHERE color = 'Y';

--SELECT code, model, speed + ram + 10*hd AS rating FROM laptop ORDER BY rating DESC, code;


--ships
--SELECT CLASS, COUNTRY FROM CLASSES WHERE NUMGUNS < 10;

--SELECT NAME AS SHIPNAME FROM SHIPS WHERE LAUNCHED < 1918;

--SELECT SHIP, BATTLE FROM OUTCOMES WHERE RESULT = 'sunk';

--SELECT NAME FROM SHIPS WHERE NAME = CLASS;

--SELECT NAME FROM SHIPS WHERE NAME LIKE 'R%';

--SELECT NAME FROM SHIPS WHERE NAME LIKE '% %' AND NAME NOT LIKE '% % %';

