--begin transaction

--CREATE TRIGGER tr1
--ON Classes
--AFTER INSERT
--AS 
--INSERT INTO SHIPS(NAME, CLASS)
--SELECT CLASS, CLASS
--FROM inserted


--INSERT INTO CLASSES(CLASS, TYPE, COUNTRY, NUMGUNS, BORE, DISPLACEMENT)
--VALUES ('Master' , 'aa', 'Bulgaria', 100, 10, 100000)

--ALTER TABLE OUTCOMES
--DROP CONSTRAINT DF_RES_SUNK

--CREATE TRIGGER tr2
--ON SHIPS
--AFTER DELETE AS
--DELETE FROM CLASSES
--WHERE CLASS NOT IN (SELECT CLASS FROM SHIPS)
--AND CLASS IN( SELECT CLASS FROM DELETED)

--SELECT * FROM SHIPS

--DROP TRIGGER tr2

--CREATE TRIGGER tr3
--ON SHIPS 
--INSTEAD OF INSERT AS
--INSERT INTO SHIPS(NAME, CLASS, LAUNCHED)
--SELECT NAME, CLASS, 
--CASE WHEN LAUNCHED > YEAR(getdate()) THEN NULL
--ELSE LAUNCHED END
--FROM INSERTED

--INSERT INTO Ships VALUES ('Test', 'Iowa', 2250)

--SELECT * FROM SHIPS

--DROP TRIGGER tr3

--CREATE TRIGGER tr4
--ON MOVIE 
--AFTER UPDATE AS
--UPDATE MOVIEEXEC
--SET NETWORTH = NETWORTH + 100000
--WHERE CERT# IN (SELECT CERT# FROM DELETED D
--                    JOIN INSERTED I ON I.YEAR = D.YEAR AND I.TITLE = D.TITLE   
--					 WHERE D.INCOLOR = 'N' AND I.INCOLOR = 'Y')




--SELECT * FROM MOVIEEXEC

--UPDATE MOVIE SET INCOLOR = 'Y' WHERE TITLE LIKE 'The Man%'

--drop trigger tr4

--CREATE TRIGGER tr5
--ON OUTCOMES
--AFTER INSERT, UPDATE
--AS 
--IF EXISTS (SELECT * FROM INSERTED
--             JOIN SHIPS ON SHIP = SHIPS.NAME
--			 JOIN BATTLES ON BATTLE = BATTLES.NAME
--			 WHERE LAUNCHED > YEAR(BATTLES.DATE))

--BEGIN 
--RAISERROR('Error: Ship is launched after battle', 16, 10)
--ROLLBACK;
--END;

--INSERT INTO Outcomes(ship, battle, result)
--VALUES ('Iowa', 'North Atlantic', 'sunk');

--DROP TRIGGER tr5


--CREATE VIEW sunkShips
--AS SELECT SHIP, BATTLE FROM OUTCOMES
--WHERE RESULT = 'sunk'

--CREATE TRIGGER tr6
--ON sunkShips
--INSTEAD OF INSERT
--AS
--INSERT INTO OUTCOMES(SHIP, BATTLE, RESULT)
--SELECT ship, battle, 'sunk'
--FROM INSERTED

--rollback transaction

begin transaction

--CREATE TRIGGER tr1
--ON Movie
--AFTER INSERT
--AS 
--INSERT INTO STARSIN(MOVIETITLE, MOVIEYEAR, STARNAME)
--SELECT TITLE, YEAR, 'Bruce Willis' FROM INSERTED
--WHERE TITLE LIKE '%save%' AND TITLE like '%world%'

--INSERT INTO MOVIESTAR
--VALUES('Bruce Willis', 'Hollywood', 'M', '1955-03-19')

--INSERT INTO MOVIE
--VALUES('save save the world Bruce!', 2002, 69, 'N', 'Fox', 555)

--SELECT * FROM movie
--select * from starsin

--DROP TRIGGER tr1

--CREATE TRIGGER tr2
--ON MOVIEEXEC 
--AFTER INSERT, UPDATE, DELETE
--AS
--IF ((SELECT AVG(NETWORTH) FROM MOVIEEXEC) < 50000)
--   BEGIN
--   RAISERROR('Data Integrity Situation', 11, 1)
--   ROLLBACK;
--   END


--   DROP TRIGGER TR2


--CREATE TRIGGER tr3 
--ON MOVIEEXEC 
--INSTEAD OF DELETE 
--AS
--UPDATE MOVIE
--SET PRODUCERC# = NULL WHERE PRODUCERC# IN (SELECT CERT# FROM DELETED)

--DELETE FROM MOVIEEXEC
--WHERE CERT# IN (SELECT CERT# FROM DELETED)



--DROP TRIGGER TR3

CREATE TRIGGER tr4
ON STARSIN
AFTER INSERT 
AS
INSERT INTO MOVIE 
SELECT MOVIETITLE, MOVIEYEAR, NULL, NULL, NULL, NULL FROM INSERTED WHERE MOVIETITLE NOT IN (SELECT TITLE FROM MOVIE)

INSERT INTO MOVIESTAR 
SELECT STARNAME, NULL, NULL, NULL FROM INSERTED WHERE STARNAME NOT IN (SELECT NAME FROM MOVIESTAR)
