--SELECT TITLE, YEAR, STUDIONAME, ADDRESS FROM Movie, STUDIO WHERE STUDIONAME = NAME AND INCOLOR = 'Y';

--SELECT TITLE, YEAR, STUDIONAME, ADDRESS FROM Movie JOIN STUDIO ON STUDIONAME = NAME WHERE INCOLOR = 'Y';

--SELECT laptop.model , PRICE, MAKER FROM laptop JOIN product ON laptop.model = product.model WHERE screen = 15;

--SELECT m1.TITLE FROM MOVIE m1, MOVIE m2 WHERE m2.title = 'Star Wars' AND m1.LENGTH > m2.LENGTH;

--SELECT NAME, TITLE FROM MOVIESTAR
--JOIN STARSIN ON NAME = STARNAME 
--JOIN MOVIE ON MOVIETITLE = TITLE 
--WHERE GENDER = 'F' AND STUDIONAME = 'MGM';


--(SELECT title, year
--FROM Movie
--WHERE incolor = 'y')
--UNION
--(SELECT movietitle, movieyear
--FROM StarsIn
--WHERE starname = 'Harrison Ford');

--(SELECT name, address
--FROM MovieStar
--WHERE gender = 'F')
--INTERSECT
--(SELECT name, address
--FROM MovieExec
--WHERE networth > 10);--SELECT NAME FROM MOVIESTAR JOIN STARSIN ON NAME = STARNAME WHERE MOVIETITLE = 'Terms of Endearment' AND GENDER = 'F';--SELECT STARNAME FROM STARSIN JOIN MOVIE ON TITLE = MOVIETITLE WHERE STUDIONAME = 'MGM' AND YEAR = '1995' ;---PCCC--SELECT SPEED, MAKER FROM LAPTOP JOIN PRODUCT ON LAPTOP.MODEL = PRODUCT.MODEL WHERE HD >= 9 ;-------(SELECT NAME, ADDRESS FROM MOVIESTAR) UNION (SELECT NAME, ADDRESS FROM MOVIESTAR WHERE GENDER = 'M' ) ORDER BY NAME DESC--SELECT U.MODEL, U.PRICE FROM PRODUCT P--JOIN ((SELECT MODEL, PRICE FROM PC) UNION (SELECT MODEL, PRICE FROM LAPTOP) UNION (SELECT MODEL, PRICE FROM printer)) U ON U.MODEL = P.MODEL WHERE MAKER = 'B' ORDER BY PRICE DESC;--(SELECT HD FROM PC) INTERSECT (SELECT HD FROM LAPTOP)--SELECT DISTINCT L.HD FROM PC L JOIN PC P ON L.CODE != P.CODE --WHERE L.HD = P.HD;--SELECT DISTINCT P1.CODE, P2.CODE FROM PC P1 JOIN PC P2 ON P1.CODE < P2.CODE WHERE P1.SPEED = P2.SPEED AND P1.RAM = P2.RAM;---SELECT DISTINCT * FROM PC P1 JOIN PRODUCT PR  ON PR.model = P1.model WHERE SPEED >= 500;--SHIPS--SELECT DISTINCT S.NAME FROM SHIPS S JOIN CLASSES C ON S.CLASS = C.CLASS WHERE DISPLACEMENT > 35000;--SELECT RES.SHIP, CL.DISPLACEMENT, CL.NUMGUNS FROM (SELECT O.SHIP FROM OUTCOMES O JOIN BATTLES BAT ON O.BATTLE=BAT.NAME WHERE BATTLE = 'Guadalcanal') RES JOIN SHIPS SH ON SH.NAME = RES.SHIP                             --  JOIN CLASSES CL ON CL.CLASS = SH.CLASS ;
--(SELECT CL.COUNTRY FROM SHIPS SS JOIN CLASSES CL ON CL.CLASS = SS.CLASS WHERE CL.TYPE = 'bb' ) INTERSECT
--(SELECT CL.COUNTRY FROM SHIPS SS JOIN CLASSES CL ON CL.CLASS = SS.CLASS WHERE CL.TYPE = 'bc') 

SELECT O1.SHIP FROM OUTCOMES O1 
  JOIN BATTLES BAT ON BAT.NAME = O1.BATTLE  
  JOIN OUTCOMES O2 ON O2.SHIP = O1.SHIP
  JOIN BATTLES BAT2 ON O2.BATTLE = BAT2.NAME
  WHERE O1.RESULT = 'damaged' AND BAT.DATE < BAT2.DATE;
    



