--SELECT * FROM printer WHERE price >= ALL (SELECT price FROM printer ); 

--SELECT TOP 1 * FROM printer WHERE price >= ALL (SELECT price FROM printer );  

--SELECT DISTINCT CLASS FROM SHIPS WHERE NAME IN (SELECT SHIP FROM OUTCOMES WHERE RESULT = 'sunk');

--SELECT DISTINCT CLASS FROM CLASSES WHERE CLASS NOT IN (SELECT CLASS FROM SHIPS WHERE NAME NOT IN (SELECT SHIP FROM OUTCOMES WHERE RESULT = 'sunk'));


--movies

--SELECT * FROM MOVIESTAR
--WHERE NAME IN (SELECT NAME FROM MOVIEEXEC WHERE NETWORTH > 10000000) AND GENDER = 'F';

--SELECT NAME FROM MOVIESTAR
--WHERE NAME NOT IN (SELECT NAME FROM MOVIEEXEC);

--PC
--SELECT DISTINCT MAKER FROM PRODUCT 
  --WHERE MODEL IN (SELECT MODEL FROM PC WHERE SPEED >= 500) ;

--SELECT * FROM LAPTOP
--WHERE SPEED < ANY (SELECT SPEED FROM PC )

--SELECT U.MODEL FROM (SELECT TOP 1 * FROM 
  --((SELECT MODEL, PRICE FROM PC) UNION (SELECT MODEL, PRICE FROM LAPTOP) UNION (SELECT MODEL, PRICE FROM PRINTER)) res ORDER BY PRICE DESC ) U

--SELECT MAKER FROM PRODUCT PR
--WHERE PR.MODEL IN (SELECT MODEL FROM PRINTER
                    -- WHERE PRICE <= ALL ( SELECT PRICE FROM PRINTER WHERE COLOR = 'Y') AND COLOR = 'Y') 
 
 --SELECT MAKER FROM PRODUCT 
 --WHERE MODEL IN (SELECT MODEL FROM PC P1
 --WHERE RAM <= ALL ( SELECT RAM FROM PC)
   --   AND SPEED >= ALL (SELECT SPEED FROM PC P2 WHERE P1.RAM = P2.RAM))


--SHIPSS
--SELECT COUNTRY FROM CLASSES 
--WHERE NUMGUNS >= ALL (SELECT NUMGUNS FROM CLASSES)

--SELECT NAME FROM SHIPS 
--WHERE CLASS IN (SELECT CLASS FROM CLASSES WHERE BORE = 16)

--SELECT BATTLE FROM OUTCOMES 
--WHERE SHIP IN (SELECT NAME FROM SHIPS WHERE CLASS = 'Kongo')









