--SELECT C.COUNTRY, S.NAME FROM SHIPS S
--JOIN CLASSES C ON S.CLASS = C.CLASS
--LEFT JOIN OUTCOMES OT ON OT.SHIP = S.NAME
--WHERE OT.SHIP IS NULL

--SELECT  * FROM CLASSES C --C.CLASS, OT.BATTLE
--LEFT JOIN SHIPS S ON S.CLASS = C.CLASS
--LEFT JOIN OUTCOMES OT ON OT.SHIP = S.NAME
--WHERE C.COUNTRY = 'Gt.Britain'

--SELECT * FROM OUTCOMES OT
--JOIN SHIPS S ON OT.SHIP = S.NAME 
--RIGHT JOIN CLASSES CL ON CL.CLASS = S.CLASS
--WHERE COUNTRY = 'Gt.Britain'

--SELECT C.CLASS, COUNTRY, S.NAME FROM CLASSES C
--JOIN SHIPS S ON C.CLASS = S.CLASS
--WHERE LAUNCHED = 1916

--SELECT * FROM CLASSES C
--LEFT JOIN SHIPS S ON C.CLASS = S.CLASS AND LAUNCHED = 1916


--ZADACHKI ZAKACHKI

--SELECT DISTINCT S.NAME, SI.STARNAME FROM STARSIN SI
--JOIN MOVIE M ON M.TITLE = SI.MOVIETITLE
--JOIN STUDIO S ON S.NAME = M.STUDIONAME
--ORDER BY S.NAME

--SELECT DISTINCT E.NAME FROM STARSIN SI
--JOIN MOVIE M ON M.TITLE = SI.MOVIETITLE 
--JOIN MOVIEEXEC E ON E.CERT# = M.PRODUCERC#
--WHERE SI.STARNAME = 'Harrison Ford'

--SELECT DISTINCT S.NAME FROM MOVIESTAR S
--JOIN STARSIN SI ON SI.STARNAME = S.NAME
--JOIN MOVIE M ON M.TITLE = SI.MOVIETITLE
--WHERE S.GENDER = 'F' AND M.STUDIONAME = 'MGM'

--SELECT M1.TITLE, E.NAME AS PRODUCER FROM MOVIE M1
--JOIN MOVIEEXEC E ON M1.PRODUCERC# = E.CERT#
--WHERE M1.PRODUCERC# = (SELECT M.PRODUCERC# FROM MOVIE M
--WHERE M.TITLE = 'Star Wars')


--SELECT M.TITLE, M.YEAR, E.NAME FROM MOVIE M
--LEFT JOIN MOVIEEXEC E ON M.PRODUCERC# = E.CERT#

--SELECT M.TITLE, M.YEAR, E.NAME, M.STUDIONAME, S.ADDRESS FROM MOVIE M
--LEFT JOIN STUDIO S ON S.NAME = M.STUDIONAME
--LEFT JOIN MOVIEEXEC E ON M.PRODUCERC# = E.CERT#

--SELECT M.NAME FROM MOVIESTAR M
--LEFT JOIN STARSIN SI ON SI.STARNAME = M.NAME
--WHERE SI.MOVIETITLE IS NULL

--PC

--SELECT P.MODEL, PC.PRICE FROM PRODUCT P
--LEFT JOIN PC ON PC.MODEL = P.MODEL
--WHERE P.TYPE = 'PC'

--SELECT MODEL, MAKER, TYPE FROM PRODUCT
--WHERE MODEL NOT IN ((SELECT MODEL FROM PC)
--UNION
--(SELECT MODEL FROM LAPTOP)
--UNION
--(SELECT MODEL FROM PRINTER))

--SHIPS

--SELECT S.NAME, CL.COUNTRY, NUMGUNS, LAUNCHED FROM SHIPS S
--JOIN CLASSES CL ON CL.CLASS = S.CLASS

