--SELECT SUM(LENGTH) AS 'SUM OF LENGTH'  FROM MOVIE
--JOIN STARSIN ON TITLE = MOVIETITLE AND YEAR = MOVIEYEAR
--WHERE STARNAME = 'Harrison Ford']

--SELECT STUDIONAME, SUM(LENGTH)
--FROM Movie
--GROUP BY studioName;


--SELECT DISTINCT STUDIONAME, (SELECT SUM(LENGTH) FROM MOVIE M2 WHERE M2.STUDIONAME = STUDIONAME) FROM MOVIE 
 
 --SELECT DISTINCT YEAR(BIRTHDATE), COUNT(NAME) FROM MOVIESTAR
 --GROUP BY YEAR(BIRTHDATE) 

-- SELECT 
--  YEAR(birthdate) AS birth_year,
--  COUNT(*) AS total_actors,
--  SUM(CASE WHEN gender = 'F' THEN 1 ELSE 0 END) AS actresses,
--  SUM(CASE WHEN gender = 'M' THEN 1 ELSE 0 END) AS actors
--FROM moviestar
--GROUP BY YEAR(birthdate);

--SELECT YEAR(BIRTHDATE), GENDER, COUNT(NAME) FROM MOVIESTAR
--GROUP BY YEAR(BIRTHDATE), GENDER

--SELECT M.NAME, COUNT(MOVIETITLE) FROM MOVIESTAR M
--LEFT JOIN STARSIN SI ON SI.STARNAME = M.NAME
--GROUP BY M.NAME

--SELECT * FROM MOVIESTAR M
--LEFT JOIN STARSIN SI ON SI.STARNAME = M.NAME


--SELECT AVG(MOVIESCOUNT) FROM 
--(SELECT COUNT(MOVIETITLE) AS MOVIESCOUNT FROM MOVIESTAR M
--LEFT JOIN STARSIN SI ON SI.STARNAME = M.NAME
--GROUP BY M.NAME) U


--ZADACHKI S PISI

--SELECT AVG(SPEED) FROM LAPTOP

--SELECT P.MAKER, AVG(SCREEN) FROM PRODUCT P
--JOIN LAPTOP L ON P.MODEL = L.MODEL
--GROUP BY P.MAKER

--SELECT AVG(SPEED) FROM (SELECT SPEED FROM LAPTOP 
--WHERE PRICE > 1000) U

--SELECT AVG(speed)
--FROM laptop
--WHERE price > 1000

--SELECT AVG(PRICE) FROM PRODUCT P
--JOIN PC PC1 ON PC1.MODEL = P.MODEL
--WHERE MAKER = 'A'

--SELECT AVG(U.PRICE) FROM ((SELECT PRICE FROM PRODUCT P1
--JOIN LAPTOP L ON L.MODEL = P1.MODEL
--WHERE MAKER = 'B')
--UNION ALL
--(SELECT PRICE FROM PRODUCT P2
--JOIN PC PC1 ON PC1.MODEL = P2.MODEL
--WHERE MAKER = 'B') )U

--SELECT SPEED, AVG(PRICE) FROM PC
--GROUP BY SPEED

--SELECT P.MAKER FROM PRODUCT P
--WHERE TYPE='PC'
--GROUP BY P.MAKER
--HAVING COUNT(P.MODEL) >= 3


--SELECT P.MAKER FROM PRODUCT P
--JOIN PC PC1 ON PC1.MODEL = P.MODEL
--WHERE PC1.PRICE >= ALL (SELECT PRICE FROM PC ) 

--SELECT DISTINCT maker
--FROM product
--   JOIN pc ON product.model = pc.model
--WHERE price = (SELECT MAX(price) FROM pc)

--SELECT SPEED, AVG(PRICE) FROM PC
--WHERE SPEED > 800
--GROUP BY SPEED

--SELECT AVG(HD) FROM PC PC1
--WHERE MODEL IN (SELECT DISTINCT P1.MODEL FROM PRODUCT P1
--JOIN PRODUCT P2 ON (P2.MAKER = P1.MAKER) AND P1.TYPE != P2.TYPE
--WHERE P1.TYPE = 'pc'  AND P2.TYPE ='printer')

--SELECT AVG(hd) AverageHD
--FROM product
--    JOIN pc on product.model = pc.model
--WHERE maker IN (SELECT maker
--                FROM product
--                WHERE type = 'Printer')

--SELECT SCREEN, MAX(PRICE) - MIN(PRICE) FROM LAPTOP
--GROUP BY SCREEN

--KORABIIIII

--SELECT COUNT(*) FROM (SELECT CLASS FROM SHIPS
--GROUP BY CLASS) U

--SELECT AVG(NUMGUNS) FROM SHIPS SH
--JOIN CLASSES CL ON SH.CLASS = CL.CLASS

--SELECT CLASS, MIN(LAUNCHED), MAX(LAUNCHED) FROM SHIPS
--GROUP BY CLASS

--SELECT CLASS, COUNT(*) FROM SHIPS SH 
--JOIN OUTCOMES OT ON OT.SHIP = SH.NAME
--WHERE RESULT = 'sunk'
--GROUP BY CLASS

--SELECT CLASS, COUNT(NAME) AS FALLEN  FROM SHIPS
--JOIN OUTCOMES ON SHIP = NAME
--WHERE CLASS IN (SELECT CLASS FROM SHIPS  
--GROUP BY CLASS
--HAVING COUNT(NAME) > 4) AND RESULT = 'SUNK' 
--GROUP BY CLASS

--SELECT COUNTRY, AVG(DISPLACEMENT) FROM CLASSES 
--GROUP BY COUNTRY


--SELECT STARNAME, COUNT(DISTINCT STUDIONAME) AS STUDIOS FROM MOVIE M
--JOIN STARSIN SI ON SI.MOVIETITLE = M.TITLE
--GROUP BY STARNAME

--SELECT S.NAME, COUNT(DISTINCT STUDIONAME) FROM MOVIESTAR S
--LEFT JOIN STARSIN SI ON SI.STARNAME = S.NAME
--LEFT JOIN MOVIE M ON M.TITLE = SI.MOVIETITLE
--GROUP BY S.NAME


--SELECT S.NAME FROM MOVIESTAR S
--LEFT JOIN STARSIN SI ON SI.STARNAME = S.NAME
--LEFT JOIN MOVIE M ON M.TITLE = SI.MOVIETITLE
--WHERE MOVIEYEAR > 1990
--GROUP BY S.NAME
--HAVING COUNT(MOVIETITLE) >= 3

