--SELECT NAME,
-- CASE GENDER 
-- WHEN 'F' THEN 'FEMALE'
-- WHEN 'M' THEN 'MALE'
-- ELSE 'UNKNOWN'
-- END AS GENDER 
-- FROM MOVIESTAR


--SELECT MODEL, PRICE,
--CASE 
--WHEN PRICE < 900 THEN 'LOW'
--WHEN PRICE > 1100 THEN 'HIGH'
--ELSE 'AVERAGE'
--END AS PRICE_RANGE
--FROM LAPTOP


--SELECT CASE
--  WHEN PRICE < 900 THEN 'LOW'
--  WHEN PRICE > 1100 THEN  'HIGH'
--  ELSE 'AVERAGE'
--  END AS STATS, COUNT(*)
--  FROM LAPTOP
--  GROUP BY CASE 
--    WHEN PRICE < 900 THEN 'LOW'
--  WHEN PRICE > 1100 THEN  'HIGH'
--  ELSE 'AVERAGE'
--  END


--SELECT BATTLE, DATE,
--SUM(CASE RESULT WHEN 'sunk' THEN 1 ELSE 0 END) AS SUNKSHIPS,
--SUM(CASE RESULT WHEN 'damaged' THEN 1 ELSE 0 END) AS DAMAGEDSHIPS,
--SUM(CASE RESULT WHEN 'ok' THEN 1 ELSE 0 END) AS OKSHIPS
--FROM OUTCOMES OT
--JOIN BATTLES BAT ON BAT.NAME = OT.BATTLE
--GROUP BY BATTLE, DATE


--zad movies
--SELECT
--CASE 
--WHEN YEAR(BIRTHDATE) < 1960  THEN 'BEFORE 60S'
--WHEN YEAR(BIRTHDATE) >= 1960 AND  YEAR(BIRTHDATE) < 1970 THEN '60S'
--WHEN YEAR(BIRTHDATE) >= 1970 AND  YEAR(BIRTHDATE) < 1980 THEN '70S'
--WHEN YEAR(BIRTHDATE) >= 1980 THEN 'AFTER 80S'
--END AS PERIODS, COUNT(*) AS NUMACTORS
--FROM MOVIESTAR
--GROUP BY CASE 
--WHEN YEAR(BIRTHDATE) < 1960  THEN 'BEFORE 60S'
--WHEN YEAR(BIRTHDATE) >= 1960 AND  YEAR(BIRTHDATE) < 1970 THEN '60S'
--WHEN YEAR(BIRTHDATE) >= 1970 AND  YEAR(BIRTHDATE) < 1980 THEN '70S'
--WHEN YEAR(BIRTHDATE) >= 1980 THEN 'AFTER 80S' END

--SELECT * FROM MOVIESTAR


--SELECT OT.BATTLE FROM SHIPS SH
--JOIN CLASSES CL ON CL.CLASS = SH.CLASS
--JOIN OUTCOMES OT ON  OT.SHIP = SH.NAME
--GROUP BY OT.BATTLE
--HAVING COUNT(CASE WHEN NUMGUNS < 9 THEN 1 ELSE 0 END) >= 3 AND COUNT(CASE WHEN RESULT='ok' THEN 1 ELSE 0 END)>=2

---obshti zadachi
--SELECT OT.BATTLE ,COUNT(*) AS USASUNK FROM SHIPS SH
--JOIN CLASSES CL ON CL.CLASS = SH.CLASS
--JOIN OUTCOMES OT ON  OT.SHIP = SH.NAME
--WHERE OT.RESULT = 'SUNK' AND CL.COUNTRY='USA'
--GROUP BY OT.BATTLE 

--SELECT OT.BATTLE ,SUM(CASE WHEN COUNTRY = 'USA' AND RESULT = 'sunk' THEN 1 ELSE 0 END) AS USASUNK FROM SHIPS SH
--JOIN CLASSES CL ON CL.CLASS = SH.CLASS
--JOIN OUTCOMES OT ON  OT.SHIP = SH.NAME
--GROUP BY OT.BATTLE 
--HAVING SUM(CASE WHEN COUNTRY = 'USA' AND RESULT = 'sunk' THEN 1 ELSE 0 END)>=1

--SELECT DISTINCT OT.BATTLE FROM SHIPS SH
--JOIN CLASSES CL ON CL.CLASS = SH.CLASS
--JOIN OUTCOMES OT ON  OT.SHIP = SH.NAME
--GROUP BY OT.BATTLE, COUNTRY
--HAVING COUNT(*) >= 3


--SELECT CL.CLASS FROM CLASSES CL
--JOIN SHIPS SH ON SH.CLASS = CL.CLASS
--GROUP BY CL.CLASS
--HAVING MAX(LAUNCHED) <= 1921


--SELECT SH.NAME, SUM(CASE WHEN RESULT='DAMAGED' THEN 1 ELSE 0 END) AS DAMAGED_BATS FROM SHIPS SH
--LEFT JOIN OUTCOMES OT ON OT.SHIP = SH.NAME
--GROUP BY SH.NAME 

--SELECT COUNTRY, COUNT(DISTINCT SH.NAME) AS TOTAL_SHIPS, SUM(CASE WHEN RESULT = 'SUNK' THEN 1 ELSE 0 END) AS SUNK_SHIPS FROM CLASSES CL
--LEFT JOIN SHIPS SH ON SH.CLASS = CL.CLASS
--LEFT JOIN OUTCOMES OT ON OT.SHIP = SH.NAME
--GROUP BY COUNTRY

--SELECT COUNTRY, COUNT(DISTINCT SH.NAME) AS TOTAL_SHIPS, SUM(CASE WHEN RESULT = 'SUNK' THEN 1 ELSE 0 END) AS SUNK_SHIPS,
--SUM(CASE WHEN RESULT = 'DAMAGED' THEN 1 ELSE 0 END)AS DAMAGED_SHIPS
--FROM CLASSES CL
--LEFT JOIN SHIPS SH ON SH.CLASS = CL.CLASS
--LEFT JOIN OUTCOMES OT ON OT.SHIP = SH.NAME
--GROUP BY COUNTRY

--SELECT CLASS, SUM(CASE WHEN RESULT = 'OK' THEN 1 ELSE 0 END) AS VICTORS FROM SHIPS SH
--LEFT JOIN OUTCOMES OT ON OT.SHIP = SH.NAME
--GROUP BY CLASS 
--HAVING COUNT( DISTINCT NAME) >= 3


--MOVIES
--SELECT U.NAME FROM (SELECT NAME, STUDIONAME, COUNT(*) AS NUM_MOVIE_PER_STUDIO FROM MOVIESTAR MS
-- JOIN STARSIN SI ON MS.NAME = SI.STARNAME
-- JOIN MOVIE M ON SI.MOVIETITLE = M.TITLE
-- GROUP BY NAME, STUDIONAME) U
 


--SELECT MS.NAME, MS.BIRTHDATE, 
--(SELECT TOP 1 M.STUDIONAME
--FROM STARSIN SI
--   JOIN MOVIE M ON SI.MOVIETITLE = M.TITLE AND SI.MOVIEYEAR = M.YEAR
--   WHERE SI.STARNAME = MS.NAME
--   GROUP BY M.STUDIONAME
--   ORDER BY COUNT(*) DESC) AS STUDIO
--   FROM MOVIESTAR MS 


--PC
--SELECT MAKER, COUNT(*) FROM PRODUCT P1
--JOIN PC PC1 ON PC1.model = P1.MODEL
--WHERE MAKER IN (SELECT MAKER FROM PRODUCT P
--JOIN PRINTER PR ON PR.model = P.model
--WHERE PR.TYPE = 'LASER'
--GROUP BY MAKER
--HAVING COUNT(*) > 1)
--GROUP BY MAKER


--SELECT P1.MAKER FROM PRODUCT P1
--JOIN LAPTOP L ON L.MODEL = P1.MODEL
--GROUP BY P1.MAKER
--HAVING AVG(PRICE) > (SELECT AVG(PRICE) FROM PRODUCT P2
--JOIN PC PC1 ON PC1.MODEL = P2.MODEL AND P2.MAKER = P1.MAKER)


--SELECT P1.MODEL FROM PRODUCT P1
--JOIN PC PC1 ON PC1.model = P1.MODEL
--GROUP BY P1.MAKER, P1.MODEL
--HAVING AVG(PC1.PRICE) < (SELECT MIN(L.PRICE) FROM PRODUCT P2
-- JOIN LAPTOP L ON L.MODEL = P2.MODEL 
-- WHERE P2.MAKER = P1.MAKER)

--SELECT pc.model
--FROM pc 
--   JOIN product p ON pc.model = p.model
--GROUP BY pc.model
--HAVING AVG(pc.price) < (SELECT MIN(price) FROM laptop
--		                   JOIN product p2 ON laptop.model = p2.model
--		                WHERE p2.maker = MIN(p.maker))


--SELECT DISTINCT TITLE, YEAR FROM MOVIE M
--JOIN STARSIN SI ON SI.MOVIETITLE = M.TITLE 
--WHERE YEAR < 1982 AND STARNAME NOT LIKE '%b%' AND STARNAME NOT LIKE '%k%'
--ORDER BY YEAR ASC

--SELECT * FROM MOVIE 
--WHERE YEAR IN (SELECT YEAR FROM MOVIE
--WHERE TITLE = 'Terms of Endearment') AND (LENGTH < (SELECT LENGTH FROM MOVIE WHERE TITLE = 'Terms of Endearment') OR LENGTH IS NULL)

--SELECT MS.NAME FROM MOVIESTAR MS
--JOIN STARSIN SI ON MS.NAME = SI.STARNAME
--JOIN MOVIE M ON M.TITLE = SI.MOVIETITLE
--WHERE MS.NAME IN (SELECT NAME FROM MOVIEEXEC) 
--GROUP BY MS.NAME
--HAVING (SUM(CASE WHEN YEAR='1980' THEN 1 ELSE 0 END) >= 1 AND SUM(CASE WHEN YEAR='1985' THEN 1 ELSE 0 END) >= 1)

--SELECT DISTINCT me.NAME
--FROM MOVIEEXEC me
--	JOIN MOVIESTAR ms ON me.NAME = ms.NAME
--	JOIN STARSIN sib ON sib.STARNAME = ms.NAME AND sib.MOVIEYEAR < 1980
--	JOIN STARSIN sia ON sia.STARNAME = ms.NAME AND sia.MOVIEYEAR > 1985

--SELECT * FROM MOVIE M1
--JOIN MOVIE M2 ON M1.YEAR < M2.YEAR AND M2.INCOLOR = 'N' AND M1.STUDIONAME = M2.STUDIONAME
--WHERE M1.TITLE IN (SELECT TOP 1 TITLE FROM MOVIE WHERE 
--INCOLOR = 'Y' ORDER BY YEAR ASC)


