
--INSERT INTO BATTLES(NAME, DATE)
--VALUES ('Denmark Strait', '1941-05-24')

--INSERT INTO MOVIESTAR(NAME, GENDER)
--VALUES ('Jennifer Aniston', 'F');


--INSERT INTO STUDIO(NAME)
--SELECT DISTINCT M.STUDIONAME FROM MOVIE M
--WHERE M.STUDIONAME NOT IN (SELECT NAME FROM STUDIO)


--DELETE FROM BATTLES
--WHERE NAME = 'Denmark Strait'

--DELETE FROM MOVIESTAR
--WHERE NAME LIKE 'Jen%'

--UPDATE PRINTER SET PRICE = PRICE * 0.9 WHERE COLOR = 'Y'

begin transaction;

--INSERT INTO MOVIESTAR(NAME, BIRTHDATE)
--VALUES('Nicole Kidman', '1967-06-20')

--DELETE FROM MOVIEEXEC
--WHERE NETWORTH < 10000000

--DELETE FROM MOVIESTAR 
--WHERE ADDRESS IS NULL

--INSERT INTO PRODUCT(MAKER, MODEL, TYPE)
--VALUES ('C', 1100, 'PC')

--INSERT INTO PC(CODE, MODEL, SPEED, RAM, HD, CD, PRICE)
--VALUES ( 12, 1100, 2400, 2048, 500, '52x', 299)

--DELETE FROM pc WHERE model = 1100;
--DELETE FROM product WHERE model = 1100;



--INSERT INTO LAPTOP(CODE, MODEL, SPEED, RAM, HD, PRICE, SCREEN)
--SELECT 
--PC.CODE + 100 AS CODE,
--PC.MODEL,
--PC.SPEED,
--PC.RAM,
--PC.HD,
--PC.PRICE + 500 AS PRICE,
--15 AS SCREEN
--FROM PC


--DELETE FROM LAPTOP WHERE MODEL IN (SELECT MODEL FROM PRODUCT 
--WHERE TYPE = 'LAPTOP' AND MAKER IN (SELECT P.MAKER FROM PRODUCT P
--GROUP BY P.MAKER
--HAVING SUM(CASE WHEN P.TYPE='PRINTER' THEN 1 ELSE 0 END) = 0))

--DELETE FROM PRODUCT 
--WHERE TYPE = 'LAPTOP' AND MAKER IN (SELECT P.MAKER FROM PRODUCT P
--GROUP BY P.MAKER
--HAVING SUM(CASE WHEN P.TYPE='PRINTER' THEN 1 ELSE 0 END) = 0)


--UPDATE PRODUCT  SET MAKER = 'A'
--WHERE MAKER = 'B'

--UPDATE PC SET PRICE = PRICE/2 , HD = HD + 50

--UPDATE LAPTOP SET SCREEN = SCREEN + 1
--WHERE MODEL IN (SELECT MODEL FROM PRODUCT WHERE MAKER = 'B')

--SHIPS
--INSERT INTO CLASSES(CLASS, TYPE, COUNTRY,  BORE, DISPLACEMENT)
--VALUES('Nelson', 'bb', 'Gt. Britain', 16, 34000)
     
--INSERT INTO SHIPS(NAME, CLASS, LAUNCHED)
--VALUES('Nelson', 'Nelson', 1927)
   
--INSERT INTO SHIPS(NAME, CLASS, LAUNCHED)
--VALUES('Rodney', 'Nelson', 1927)

--DELETE FROM OUTCOMES WHERE RESULT = 'sunk'

--DELETE FROM SHIPS
--WHERE NAME NOT IN (SELECT SHIP FROM OUTCOMES )

--UPDATE CLASSES SET BORE = 2.54*BORE, DISPLACEMENT = 0.9*DISPLACEMENT

--DELETE FROM OUTCOMES WHERE SHIP IN (SELECT NAME FROM SHIPS 
--WHERE CLASS IN (SELECT DISTINCT CL.CLASS FROM CLASSES CL
--JOIN SHIPS SH ON SH.CLASS = CL.CLASS
--GROUP BY CL.CLASS 
--HAVING COUNT(*) < 3))

--DELETE FROM SHIPS 
--WHERE CLASS IN (SELECT DISTINCT CL.CLASS FROM CLASSES CL
--JOIN SHIPS SH ON SH.CLASS = CL.CLASS
--GROUP BY CL.CLASS 
--HAVING COUNT(*) < 3)

--DELETE FROM CLASSES 
--WHERE CLASS NOT IN (SELECT CLASS FROM SHIPS)

rollback transaction








