--SELECT AVG(NETWORTH)
--FROM MOVIEEXEC

--SELECT COUNT(*) FROM STARSIN

--SELECT COUNT(DISTINCT STARNAME) AS CNT FROM STARSIN

--SELECT SUM(LENGTH) FROM MOVIE M 
--JOIN STARSIN S ON S.MOVIETITLE = M.TITLE AND YEAR = MOVIEYEAR 
--WHERE STARNAME = 'HARRISON FORD';

--SELECT STUDIONAME, SUM(LENGTH) AS SUMLEN FROM MOVIE
--GROUP BY STUDIONAME 

--SELECT YEAR(BIRTHDATE) AS YEAR , COUNT(NAME) AS NAMES FROM MOVIESTAR
--GROUP BY YEAR(BIRTHDATE)


--SELECT YEAR(BIRTHDATE) AS YEAR , GENDER, COUNT(NAME) FROM MOVIESTAR
--GROUP BY YEAR(BIRTHDATE), GENDER

--SELECT TITLE FROM MOVIE WHERE
--LENGTH = (SELECT MAX(LENGTH) FROM MOVIE)

--SELECT STUDIONAME, SUM(LENGTH) FROM MOVIE
--GROUP BY STUDIONAME 
--HAVING COUNT(TITLE) >= 2

--SELECT M.NAME, COUNT(MOVIETITLE) FROM MOVIESTAR M
--LEFT JOIN STARSIN S ON S.STARNAME =  M.NAME
--GROUP BY M.NAME

--SELECT AVG(U.CUNT) FROM (SELECT COUNT(SI.MOVIETITLE) AS CUNT FROM MOVIESTAR M
--LEFT JOIN STARSIN SI ON SI.STARNAME = M.NAME
--GROUP BY M.NAME) U


---PC
--SELECT AVG(SPEED) FROM laptop

--SELECT MAKER, AVG(SCREEN) AS AVERAGE FROM PRODUCT P
--LEFT JOIN LAPTOP L ON L.MODEL = P.MODEL
--WHERE P.TYPE='Laptop'
--GROUP BY maker


--SELECT AVG(SPEED) FROM LAPTOP WHERE PRICE > 1000

--SELECT AVG(PRICE) FROM PRODUCT P
--JOIN PC PC1 ON PC1.MODEL = P.MODEL AND P.MAKER = 'A'

--SELECT AVG(U.PRICE) FROM ((SELECT PRICE FROM PRODUCT P
--JOIN PC PC1 ON PC1.MODEL = P.MODEL AND MAKER = 'B')
--UNION ALL
--(SELECT PRICE FROM PRODUCT P
--JOIN LAPTOP L ON L.MODEL = P.MODEL AND MAKER = 'B')) U


--SELECT SPEED, AVG(PRICE) AS AVERAGE FROM PC
--GROUP BY SPEED

--SELECT MAKER FROM PRODUCT 
--WHERE TYPE = 'PC'
--GROUP BY MAKER 
--HAVING COUNT(MODEL) >= 3

--SELECT MAKER FROM PRODUCT P
--JOIN PC PC1 ON PC1.MODEL = P.MODEL 
--WHERE PRICE = (SELECT MAX(PRICE) FROM PC)

--SELECT SPEED, AVG(PRICE) AS PRICE FROM PC
--GROUP BY SPEED 
--HAVING SPEED > 800


--SELECT AVG(HD) FROM PRODUCT PR
--JOIN PC PC1 ON PC1.MODEL = PR.MODEL 
--WHERE PR.MAKER IN (SELECT DISTINCT P1.MAKER FROM PRODUCT P1
--JOIN PRODUCT P2 ON P2.MAKER =  P1.MAKER AND P1.TYPE = 'printer' AND P2.TYPE = 'pc')

--SELECT SCREEN, MAX(PRICE)- MIN(PRICE) AS RATIO FROM LAPTOP 
--GROUP BY SCREEN

--SHIPS
